import type { Metadata } from "next";
// import {  Poppins } from "next/font/google";
import { Outfit } from "next/font/google";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

// const poppins = Poppins({
//   variable: "--font-poppins",
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// });
const outfit = Outfit({
  variable : "--font-outfit",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Gypsum Construction",
  description: "Generated by MasRzkyy",
  icons: {
    icon: "/favicon.ico",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
